//! TypeScript types artefact generation + drift gate.
//!
//! Generates `crates/aozora-flavored-markdown-wasm/types/aozora_flavored_markdown_types.d.ts` from the live IR
//! type tree (`aozora_flavored_markdown::ir`) plus aozora-flavored-markdown-wasm's wire envelope. The
//! output is a camelCase, `kind`-discriminated `.d.ts` consumed by the
//! playground and (downstream) `aozora-flavored-markdown-obsidian/src/ir/types.ts`.
//!
//! `types check` is the CI drift gate: it re-renders in memory and
//! byte-compares against the committed artefact, failing if they
//! diverge (so a forgotten regeneration is caught before merge).
//!
//! # Single source of truth
//!
//! Unlike a derive-based generator, the `.d.ts` body is hand-written
//! string assembly (mirroring the sibling aozora repo's xtask). Three
//! mechanisms keep it honest against the Rust types:
//!
//! 1. **Variant completeness** — `assert_*_variants` exhaustive matches
//!    in `aozora_flavored_markdown::ir::types` make a new `IrBlock` / `IrInline`
//!    variant a *compile* error until the generated union is updated.
//!    They live in the owning crate because those enums are
//!    `#[non_exhaustive]` (ADR-0013), which forbids an out-of-crate
//!    exhaustive match.
//! 2. **Field completeness** — a test serialises a fully-populated
//!    sample of every IR type and asserts each emitted wire key appears
//!    as a property in the rendered `.d.ts`.
//! 3. **Tag correctness** — a test asserts every serialised `kind` tag
//!    appears verbatim in the rendered union.
//!
//! The wire envelope types (`RenderResult` etc.) are private structs in
//! aozora-flavored-markdown-wasm, so they are hand-coded here and guarded only by the
//! byte-compare gate + review (the same treatment aozora gives its own
//! envelopes).

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::{TypesArgs, TypesOp};

const TYPES_REL_PATH: &str =
    "crates/aozora-flavored-markdown-wasm/types/aozora_flavored_markdown_types.d.ts";

pub(crate) fn dispatch(args: &TypesArgs) -> Result<()> {
    match args.op {
        TypesOp::Ts => dump(),
        TypesOp::Check => check(),
    }
}

fn workspace_root() -> Result<PathBuf> {
    // `CARGO_MANIFEST_DIR` is `<root>/crates/xtask`; the workspace root
    // is two levels up. Baked at compile time — xtask is always run via
    // `cargo run -p xtask` from inside the workspace.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let Some(root) = Path::new(manifest_dir).parent().and_then(Path::parent) else {
        bail!("could not derive workspace root from CARGO_MANIFEST_DIR={manifest_dir}");
    };
    Ok(root.to_path_buf())
}

fn dump() -> Result<()> {
    let path = workspace_root()?.join(TYPES_REL_PATH);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create_dir_all {}", parent.display()))?;
    }
    fs::write(&path, render()).with_context(|| format!("write {}", path.display()))?;
    println!("types ts: wrote {}", path.display());
    Ok(())
}

fn check() -> Result<()> {
    let path = workspace_root()?.join(TYPES_REL_PATH);
    let stored = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    if render() != stored {
        bail!(
            "TypeScript types drift detected in {TYPES_REL_PATH}: \
             run `just types` (or `cargo run -p xtask -- types ts`) to regenerate, \
             then commit the diff"
        );
    }
    println!("types check: {TYPES_REL_PATH} up to date");
    Ok(())
}

// ===================================================================
// Codegen
// ===================================================================

fn render() -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(POSITIONS);
    out.push_str(INLINE);
    out.push_str(BLOCK);
    out.push_str(DOCUMENT);
    out.push_str(ENVELOPE);
    out
}

const HEADER: &str = "// AUTO-GENERATED by `cargo run -p xtask -- types ts` — DO NOT EDIT BY HAND.
// Regenerate with `just types`; commit the diff.
// Drift-gated in CI by `just types-check` (`xtask types check`).
//
// Single source of truth: `aozora_flavored_markdown::ir` (the IrDocument tree) plus
// aozora-flavored-markdown-wasm's wire envelope. The IR is a camelCase, `kind`-discriminated
// union mirrored by aozora-flavored-markdown-obsidian/src/ir/types.ts.

";

const POSITIONS: &str = "// =========================================================
// Source positions
// =========================================================

/** 1-based line / column tuple (comrak Sourcepos; grapheme-blind column). */
export interface Position {
  line: number;
  column: number;
}

/** Source-position range, end-exclusive (1-based line / column). */
export interface Range {
  start: Position;
  end: Position;
}

";

const INLINE: &str = "// =========================================================
// Inline nodes (discriminated on `kind`)
// =========================================================

/** Emphasis-dot / sideline style (mirrors aozora BoutenKind). */
export type BoutenStyle =
  | \"goma\"
  | \"whiteSesame\"
  | \"circle\"
  | \"whiteCircle\"
  | \"doubleCircle\"
  | \"janome\"
  | \"cross\"
  | \"whiteTriangle\"
  | \"wavyLine\"
  | \"underLine\"
  | \"doubleUnderLine\"
  | \"unknown\";

/** Which side of the text a bouten sits on. */
export type BoutenPosition = \"right\" | \"left\" | \"unknown\";

/** Resolved annotation classification (mirrors aozora AnnotationKind). */
export type AnnotationKind =
  | \"unknown\"
  | \"asIs\"
  | \"textualNote\"
  | \"invalidRubySpan\"
  | \"warichuOpen\"
  | \"warichuClose\";

export type IrInline =
  | { kind: \"text\"; value: string; range?: Range }
  | { kind: \"code\"; value: string; range?: Range }
  | { kind: \"strong\"; children: IrInline[]; range?: Range }
  | { kind: \"emphasis\"; children: IrInline[]; range?: Range }
  | { kind: \"link\"; href: string; title?: string; children: IrInline[]; range?: Range }
  | { kind: \"image\"; url: string; title?: string; alt: IrInline[]; range?: Range }
  | { kind: \"lineBreak\"; hard: boolean; range?: Range }
  | { kind: \"ruby\"; base: IrInline[]; reading: string; explicit: boolean; range?: Range }
  | { kind: \"doubleRuby\"; base: IrInline[]; range?: Range }
  | { kind: \"bouten\"; children: IrInline[]; style: BoutenStyle; position: BoutenPosition; range?: Range }
  | { kind: \"gaiji\"; codepoint?: string; description?: string; fallbackText?: string; range?: Range }
  | { kind: \"tcy\"; text: string; range?: Range }
  | { kind: \"annotation\"; payload: string; resolved?: AnnotationKind; range?: Range };

";

const BLOCK: &str = "// =========================================================
// Block nodes (discriminated on `kind`)
// =========================================================

/** Table cell alignment (GFM). */
export type IrTableAlign = \"left\" | \"center\" | \"right\" | \"default\";

/** Paired-container subtype (mirrors aozora ContainerKind). */
export type ContainerSubtype = \"indent\" | \"alignEnd\" | \"keigakomi\" | \"warichu\" | \"unknown\";

/** Section-break subtype (mirrors aozora SectionKind). */
export type SectionSubtype = \"choho\" | \"dan\" | \"spread\" | \"unknown\";

/** One table row: a list of cells, each a list of inline runs. */
export interface IrTableRow {
  cells: IrInline[][];
  range?: Range;
}

/** One list item: a list of block children. */
export interface IrListItem {
  children: IrBlock[];
  range?: Range;
}

export type IrBlock =
  | { kind: \"paragraph\"; children: IrInline[]; sourceLine?: number; range?: Range }
  | { kind: \"heading\"; level: number; children: IrInline[]; sourceLine?: number; range?: Range }
  | { kind: \"blockquote\"; children: IrBlock[]; sourceLine?: number; range?: Range }
  | { kind: \"list\"; ordered: boolean; start?: number; items: IrListItem[]; sourceLine?: number; range?: Range }
  | { kind: \"codeBlock\"; lang?: string; value: string; sourceLine?: number; range?: Range }
  | { kind: \"thematicBreak\"; sourceLine?: number; range?: Range }
  | { kind: \"table\"; header: IrTableRow; rows: IrTableRow[]; align: IrTableAlign[]; sourceLine?: number; range?: Range }
  | { kind: \"container\"; subtype: ContainerSubtype; children: IrBlock[]; indentLevel?: number; sourceLine?: number; range?: Range }
  | { kind: \"pageBreak\"; sourceLine?: number; range?: Range }
  | { kind: \"sectionBreak\"; subtype: SectionSubtype; sourceLine?: number; range?: Range };

";

const DOCUMENT: &str = "// =========================================================
// Document root
// =========================================================

/** Structured IR document — root of the `kind`-discriminated tree. */
export interface IrDocument {
  blocks: IrBlock[];
}

";

const ENVELOPE: &str = "// =========================================================
// WASM wire envelope (aozora-flavored-markdown-wasm renderAfm / renderBlocks)
//
// Mirrors the private `#[derive(Serialize)]` structs in
// aozora-flavored-markdown-wasm/src/lib.rs. Hand-maintained (the structs are private, so not
// introspectable here) and guarded by the byte-compare drift gate.
// =========================================================

export type Severity = \"error\" | \"warning\" | \"note\";
export type DiagnosticSource = \"source\" | \"internal\";

/** Byte-offset span into the (sanitized) source, end-exclusive. */
export interface Span {
  start: number;
  end: number;
}

/** A render diagnostic (lexer or afm host-level), serialised by the wasm bridge. Mirrors `aozora_flavored_markdown::Diagnostic`. */
export interface Diagnostic {
  severity: Severity;
  source: DiagnosticSource;
  code: string;
  message: string;
  span: Span;
}

/** Result envelope returned by `renderAfm`. */
export interface RenderResult {
  ir: IrDocument;
  html: string;
  diagnostics: Diagnostic[];
}

/** One entry of `renderBlocks` (per top-level comrak block). */
export interface BlockResult {
  ir: IrBlock[];
  html: string;
  sourceLine: number;
}

/** Result envelope returned by `renderBlocks`. */
export interface BlocksResult {
  blocks: BlockResult[];
  diagnostics: Diagnostic[];
}

/** Optional render configuration accepted from JS by `renderAfm`. */
export interface RenderOptions {
  aozoraEnabled?: boolean;
  sourceLineAnchors?: boolean;
}
";

// Variant-completeness witnesses now live in `aozora_flavored_markdown::ir::types`
// (the crate that owns `IrBlock` / `IrInline`): those enums are
// `#[non_exhaustive]` (ADR-0013), so an exhaustive match is only possible
// in the owning crate. The field- and tag-completeness tests below still
// guard the hand-written `.d.ts` union from here.

#[cfg(test)]
mod tests {
    use aozora_flavored_markdown::ir::{
        AnnotationKind, BoutenPosition, BoutenStyle, ContainerSubtype, IrBlock, IrDocument,
        IrInline, IrListItem, IrTableAlign, IrTableRow, Position, Range, SectionSubtype,
    };
    use serde::Serialize;
    use serde_json::Value;

    use super::render;

    fn to_value(v: impl Serialize) -> Value {
        serde_json::to_value(v).expect("IR sample serialises")
    }

    fn rng() -> Range {
        Range {
            start: Position { line: 1, column: 1 },
            end: Position { line: 1, column: 2 },
        }
    }

    /// One fully-populated sample of every public IR type (all `Option`
    /// fields `Some`) so each wire key is exercised. Split by node family
    /// to stay within the per-function line budget.
    fn samples() -> Vec<Value> {
        let mut all = block_samples();
        all.extend(inline_samples());
        all.extend(struct_samples());
        all
    }

    fn block_samples() -> Vec<Value> {
        vec![
            to_value(IrBlock::Paragraph {
                children: vec![],
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::Heading {
                level: 2,
                children: vec![],
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::Blockquote {
                children: vec![],
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::List {
                ordered: true,
                start: Some(3),
                items: vec![],
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::CodeBlock {
                lang: Some("rust".to_owned()),
                value: "x".to_owned(),
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::ThematicBreak {
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::Table {
                header: IrTableRow {
                    cells: vec![],
                    range: Some(rng()),
                },
                rows: vec![],
                align: vec![IrTableAlign::Left],
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::Container {
                subtype: ContainerSubtype::Indent,
                children: vec![],
                indent_level: Some(2),
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::PageBreak {
                source_line: Some(1),
                range: Some(rng()),
            }),
            to_value(IrBlock::SectionBreak {
                subtype: SectionSubtype::Dan,
                source_line: Some(1),
                range: Some(rng()),
            }),
        ]
    }

    fn inline_samples() -> Vec<Value> {
        vec![
            to_value(IrInline::Text {
                value: "t".to_owned(),
                range: Some(rng()),
            }),
            to_value(IrInline::Code {
                value: "c".to_owned(),
                range: Some(rng()),
            }),
            to_value(IrInline::Strong {
                children: vec![],
                range: Some(rng()),
            }),
            to_value(IrInline::Emphasis {
                children: vec![],
                range: Some(rng()),
            }),
            to_value(IrInline::Link {
                href: "h".to_owned(),
                title: Some("ti".to_owned()),
                children: vec![],
                range: Some(rng()),
            }),
            to_value(IrInline::Image {
                url: "u".to_owned(),
                title: Some("ti".to_owned()),
                alt: vec![],
                range: Some(rng()),
            }),
            to_value(IrInline::LineBreak {
                hard: true,
                range: Some(rng()),
            }),
            to_value(IrInline::Ruby {
                base: vec![],
                reading: "r".to_owned(),
                explicit: true,
                range: Some(rng()),
            }),
            to_value(IrInline::DoubleRuby {
                base: vec![],
                range: Some(rng()),
            }),
            to_value(IrInline::Bouten {
                children: vec![],
                style: BoutenStyle::Goma,
                position: BoutenPosition::Right,
                range: Some(rng()),
            }),
            to_value(IrInline::Gaiji {
                codepoint: Some("U+5650".to_owned()),
                description: Some("d".to_owned()),
                fallback_text: Some("f".to_owned()),
                range: Some(rng()),
            }),
            to_value(IrInline::Tcy {
                text: "12".to_owned(),
                range: Some(rng()),
            }),
            to_value(IrInline::Annotation {
                payload: "p".to_owned(),
                resolved: Some(AnnotationKind::Unknown),
                range: Some(rng()),
            }),
        ]
    }

    fn struct_samples() -> Vec<Value> {
        vec![
            to_value(IrDocument { blocks: vec![] }),
            to_value(IrTableRow {
                cells: vec![],
                range: Some(rng()),
            }),
            to_value(IrListItem {
                children: vec![],
                range: Some(rng()),
            }),
            to_value(Position { line: 1, column: 2 }),
        ]
    }

    fn object_keys(v: &Value) -> Vec<String> {
        match v {
            Value::Object(map) => map.keys().cloned().collect(),
            _ => vec![],
        }
    }

    /// Every wire field emitted by serde must be declared (as `x:` or
    /// `x?:`) somewhere in the generated `.d.ts`. Catches "added a field
    /// in Rust, forgot the generator".
    #[test]
    fn generated_ts_declares_every_wire_field() {
        let ts = render();
        for sample in samples() {
            for key in object_keys(&sample) {
                let required = format!("{key}:");
                let optional = format!("{key}?:");
                assert!(
                    ts.contains(&required) || ts.contains(&optional),
                    "wire field `{key}` is missing from the generated .d.ts — \
                     update the union/interface literals in xtask/src/types.rs"
                );
            }
        }
    }

    /// Every serialised `kind` tag must appear verbatim in the generated
    /// union. Pins the camelCase tag strings (e.g. `codeBlock`) to serde's
    /// actual output, not a hand-typed guess.
    #[test]
    fn generated_ts_declares_every_kind_tag() {
        let ts = render();
        for sample in samples() {
            if let Some(Value::String(tag)) = sample.get("kind") {
                let needle = format!("kind: \"{tag}\"");
                assert!(
                    ts.contains(&needle),
                    "wire `kind` tag `{tag}` is missing from the generated .d.ts — \
                     update the IrInline/IrBlock union in xtask/src/types.rs"
                );
            }
        }
    }

    /// The drift gate's renderer must produce a non-empty, stable document.
    #[test]
    fn render_is_nonempty_and_ends_with_newline() {
        let ts = render();
        assert!(
            ts.contains("export interface IrDocument"),
            "missing IrDocument: {ts}"
        );
        assert!(
            ts.trim_end().ends_with('}'),
            "should end with the final interface close brace"
        );
    }
}
