// AUTO-GENERATED by `cargo run -p xtask -- types ts` — DO NOT EDIT BY HAND.
// Regenerate with `just types`; commit the diff.
// Drift-gated in CI by `just types-check` (`xtask types check`).
//
// Single source of truth: `aozora_flavored_markdown::ir` (the IrDocument tree) plus
// aozora-flavored-markdown-wasm's wire envelope. The IR is a camelCase, `kind`-discriminated
// union mirrored by aozora-flavored-markdown-obsidian/src/ir/types.ts.

// =========================================================
// Source positions
// =========================================================

/** 1-based line / column tuple (comrak Sourcepos; grapheme-blind column). */
export interface Position {
  line: number;
  column: number;
}

/** Source-position range, end-exclusive (1-based line / column). */
export interface Range {
  start: Position;
  end: Position;
}

// =========================================================
// Inline nodes (discriminated on `kind`)
// =========================================================

/** Emphasis-dot / sideline style (mirrors aozora BoutenKind). */
export type BoutenStyle =
  | "goma"
  | "whiteSesame"
  | "circle"
  | "whiteCircle"
  | "doubleCircle"
  | "janome"
  | "cross"
  | "whiteTriangle"
  | "wavyLine"
  | "underLine"
  | "doubleUnderLine"
  | "unknown";

/** Which side of the text a bouten sits on. */
export type BoutenPosition = "right" | "left" | "unknown";

/** Resolved annotation classification (mirrors aozora AnnotationKind). */
export type AnnotationKind =
  | "unknown"
  | "asIs"
  | "textualNote"
  | "invalidRubySpan"
  | "warichuOpen"
  | "warichuClose";

export type IrInline =
  | { kind: "text"; value: string; range?: Range }
  | { kind: "code"; value: string; range?: Range }
  | { kind: "strong"; children: IrInline[]; range?: Range }
  | { kind: "emphasis"; children: IrInline[]; range?: Range }
  | { kind: "link"; href: string; title?: string; children: IrInline[]; range?: Range }
  | { kind: "image"; url: string; title?: string; alt: IrInline[]; range?: Range }
  | { kind: "lineBreak"; hard: boolean; range?: Range }
  | { kind: "ruby"; base: IrInline[]; reading: string; explicit: boolean; range?: Range }
  | { kind: "doubleRuby"; base: IrInline[]; range?: Range }
  | { kind: "bouten"; children: IrInline[]; style: BoutenStyle; position: BoutenPosition; range?: Range }
  | { kind: "gaiji"; codepoint?: string; description?: string; fallbackText?: string; range?: Range }
  | { kind: "tcy"; text: string; range?: Range }
  | { kind: "annotation"; payload: string; resolved?: AnnotationKind; range?: Range };

// =========================================================
// Block nodes (discriminated on `kind`)
// =========================================================

/** Table cell alignment (GFM). */
export type IrTableAlign = "left" | "center" | "right" | "default";

/** Paired-container subtype (mirrors aozora ContainerKind). */
export type ContainerSubtype = "indent" | "alignEnd" | "keigakomi" | "warichu" | "unknown";

/** Section-break subtype (mirrors aozora SectionKind). */
export type SectionSubtype = "choho" | "dan" | "spread" | "unknown";

/** One table row: a list of cells, each a list of inline runs. */
export interface IrTableRow {
  cells: IrInline[][];
  range?: Range;
}

/** One list item: a list of block children. */
export interface IrListItem {
  children: IrBlock[];
  range?: Range;
}

export type IrBlock =
  | { kind: "paragraph"; children: IrInline[]; sourceLine?: number; range?: Range }
  | { kind: "heading"; level: number; children: IrInline[]; sourceLine?: number; range?: Range }
  | { kind: "blockquote"; children: IrBlock[]; sourceLine?: number; range?: Range }
  | { kind: "list"; ordered: boolean; start?: number; items: IrListItem[]; sourceLine?: number; range?: Range }
  | { kind: "codeBlock"; lang?: string; value: string; sourceLine?: number; range?: Range }
  | { kind: "thematicBreak"; sourceLine?: number; range?: Range }
  | { kind: "table"; header: IrTableRow; rows: IrTableRow[]; align: IrTableAlign[]; sourceLine?: number; range?: Range }
  | { kind: "container"; subtype: ContainerSubtype; children: IrBlock[]; indentLevel?: number; sourceLine?: number; range?: Range }
  | { kind: "pageBreak"; sourceLine?: number; range?: Range }
  | { kind: "sectionBreak"; subtype: SectionSubtype; sourceLine?: number; range?: Range };

// =========================================================
// Document root
// =========================================================

/** Structured IR document — root of the `kind`-discriminated tree. */
export interface IrDocument {
  blocks: IrBlock[];
}

// =========================================================
// WASM wire envelope (aozora-flavored-markdown-wasm renderAfm / renderBlocks)
//
// Mirrors the private `#[derive(Serialize)]` structs in
// aozora-flavored-markdown-wasm/src/lib.rs. Hand-maintained (the structs are private, so not
// introspectable here) and guarded by the byte-compare drift gate.
// =========================================================

export type Severity = "error" | "warning" | "note";
export type DiagnosticSource = "source" | "internal";

/** Byte-offset span into the (sanitized) source, end-exclusive. */
export interface Span {
  start: number;
  end: number;
}

/** A render diagnostic (lexer or afm host-level), serialised by the wasm bridge. Mirrors `aozora_flavored_markdown::Diagnostic`. */
export interface Diagnostic {
  severity: Severity;
  source: DiagnosticSource;
  code: string;
  message: string;
  span: Span;
}

/** Result envelope returned by `renderAfm`. */
export interface RenderResult {
  ir: IrDocument;
  html: string;
  diagnostics: Diagnostic[];
}

/** One entry of `renderBlocks` (per top-level comrak block). */
export interface BlockResult {
  ir: IrBlock[];
  html: string;
  sourceLine: number;
}

/** Result envelope returned by `renderBlocks`. */
export interface BlocksResult {
  blocks: BlockResult[];
  diagnostics: Diagnostic[];
}

/** Optional render configuration accepted from JS by `renderAfm`. */
export interface RenderOptions {
  aozoraEnabled?: boolean;
  sourceLineAnchors?: boolean;
}
