// AUTO-GENERATED by `cargo run -p xtask -- types ts` — DO NOT EDIT BY HAND.
// Regenerate with `just types`; commit the diff.
// Drift-gated in CI by `just types-check` (`xtask types check`).
//
// Single source of truth: `aozora_flavored_markdown::ir` (the IrDocument tree) plus
// aozora-flavored-markdown-wasm's wire envelope. The IR is a camelCase, `kind`-discriminated
// union mirrored by aozora-flavored-markdown-obsidian/src/ir/types.ts.

// =========================================================
// Source positions
// =========================================================

/** 1-based line / column tuple (comrak Sourcepos; grapheme-blind column). */
export interface Position {
  line: number;
  column: number;
}

/** Source-position range, end-exclusive (1-based line / column). */
export interface Range {
  start: Position;
  end: Position;
}

// =========================================================
// Inline nodes (discriminated on `kind`)
// =========================================================

export type IrInline =
  | { kind: "text"; value: string; range?: Range }
  | { kind: "code"; value: string; range?: Range }
  | { kind: "strong"; children: IrInline[]; range?: Range }
  | { kind: "emphasis"; children: IrInline[]; range?: Range }
  | { kind: "link"; href: string; title?: string; children: IrInline[]; range?: Range }
  | { kind: "image"; url: string; title?: string; alt: IrInline[]; range?: Range }
  | { kind: "lineBreak"; hard: boolean; range?: Range }
  | { kind: "ruby"; base: IrInline[]; reading: string; explicit: boolean; range?: Range }
  | { kind: "doubleRuby"; base: IrInline[]; range?: Range }
  | { kind: "bouten"; children: IrInline[]; style: string; position: string; range?: Range }
  | { kind: "gaiji"; codepoint?: string; description?: string; fallbackText?: string; range?: Range }
  | { kind: "tcy"; text: string; range?: Range }
  | { kind: "annotation"; payload: string; resolved?: string; range?: Range };

// =========================================================
// Block nodes (discriminated on `kind`)
// =========================================================

/** Table cell alignment (GFM). */
export type IrTableAlign = "left" | "center" | "right" | "default";

/** One table row: a list of cells, each a list of inline runs. */
export interface IrTableRow {
  cells: IrInline[][];
  range?: Range;
}

/** One list item: a list of block children. */
export interface IrListItem {
  children: IrBlock[];
  range?: Range;
}

export type IrBlock =
  | { kind: "paragraph"; children: IrInline[]; sourceLine?: number; range?: Range }
  | { kind: "heading"; level: number; children: IrInline[]; sourceLine?: number; range?: Range }
  | { kind: "blockquote"; children: IrBlock[]; sourceLine?: number; range?: Range }
  | { kind: "list"; ordered: boolean; start?: number; items: IrListItem[]; sourceLine?: number; range?: Range }
  | { kind: "codeBlock"; lang?: string; value: string; sourceLine?: number; range?: Range }
  | { kind: "thematicBreak"; sourceLine?: number; range?: Range }
  | { kind: "table"; header: IrTableRow; rows: IrTableRow[]; align: IrTableAlign[]; sourceLine?: number; range?: Range }
  | { kind: "container"; subtype: string; children: IrBlock[]; indentLevel?: number; sourceLine?: number; range?: Range }
  | { kind: "pageBreak"; sourceLine?: number; range?: Range }
  | { kind: "sectionBreak"; subtype: string; sourceLine?: number; range?: Range };

// =========================================================
// Document root
// =========================================================

/** One diagnostic emitted by the IR walk (distinct from the wire `Diagnostic`). */
export interface IrDiagnostic {
  level: string;
  message: string;
  code?: string;
  range?: Range;
}

/** Structured IR document — root of the `kind`-discriminated tree. */
export interface IrDocument {
  blocks: IrBlock[];
  diagnostics: IrDiagnostic[];
}

// =========================================================
// WASM wire envelope (aozora-flavored-markdown-wasm renderAfm / renderBlocks)
//
// Mirrors the private `#[derive(Serialize)]` structs in
// aozora-flavored-markdown-wasm/src/lib.rs. Hand-maintained (the structs are private, so not
// introspectable here) and guarded by the byte-compare drift gate.
// =========================================================

export type DiagnosticLevel = "error" | "warning" | "note";
export type DiagnosticSource = "source" | "internal";

/** Diagnostic projection on the JS wire (aozora-flavored-markdown-wasm `DiagnosticOut`). */
export interface Diagnostic {
  level: DiagnosticLevel;
  source: DiagnosticSource;
  code: string;
  message: string;
}

/** Result envelope returned by `renderAfm`. */
export interface RenderResult {
  ir: IrDocument;
  html: string;
  diagnostics: Diagnostic[];
}

/** One entry of `renderBlocks` (per top-level comrak block). */
export interface BlockResult {
  ir: IrBlock[];
  html: string;
  sourceLine: number;
}

/** Result envelope returned by `renderBlocks`. */
export interface BlocksResult {
  blocks: BlockResult[];
  diagnostics: Diagnostic[];
}

/** Optional render configuration accepted from JS by `renderAfm`. */
export interface RenderOptions {
  aozoraEnabled?: boolean;
  sourceLineAnchors?: boolean;
}
